AWSTemplateFormatVersion: "2010-09-09"
Description: Cloudformation for precious check api service
Parameters:
  ImageVersion:
    Type: String
  DBPassword:
    Type: String
  DBUsername:
    Type: String
Resources:
  PreciousService:
    Type: AWS::ECS::Service
    Properties:
      TaskDefinition: !Ref PreciousTaskDefinition
      Cluster: preciouscheck
      DesiredCount: 2
      ServiceName: preciouscheck-service
      DeploymentConfiguration:
        MaximumPercent: 200
        MinimumHealthyPercent: 50

  PreciousTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: preciouscheck-ecs-service
      NetworkMode: host
      ContainerDefinitions:
      - Name: main
        Image: !Join ['',['preciouscheck/precious-check-api:', !Ref ImageVersion]]
        Memory: 300
        Cpu: 2048
        Environment:
        - Name: db_url
          Value: preciouscheckdb.cluster-clwgmh3zsmsd.us-east-1.rds.amazonaws.com/preciousdb
        - Name: db_username
          Value: !Ref DBUsername
        - Name: db_password
          Value: !Ref DBPassword



